DROP DATABASE IF EXISTS DELIVERY;

CREATE DATABASE DELIVERY;
USE DELIVERY;

DROP TABLE IF EXISTS ENDERECO;
CREATE TABLE ENDERECO (
  COD_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR (250),
  COMPLEMENTO VARCHAR (250),
  BAIRRO VARCHAR (250) NOT NULL,
  NUMERO VARCHAR(5) NOT NULL,
  RUA VARCHAR (250) NOT NULL,
  CEP CHAR (8),
  FK_COD_CLIENTE INT NOT NULL,
  FOREIGN KEY (FK_COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)
);

DROP TABLE IF EXISTS CLIENTE;
CREATE TABLE CLIENTE (
  COD_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR (250) NOT NULL,
  EMAIL VARCHAR (250) NOT NULL UNIQUE,
  SENHA VARCHAR (250) NOT NULL,
  TELEFONE CHAR (11)
);

DROP TABLE IF EXISTS CUPOM;
CREATE TABLE CUPOM (
  COD_CUPOM INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR (250) NOT NULL,
  PORCENTAGEM_DESCONTO DECIMAL (5,2),
  VALOR_DESCONTO DECIMAL (9,2),
  DATA_VALIDADE DATETIME,
  QUANTIDADE INT
);

DROP TABLE IF EXISTS FUNCIONARIO;
CREATE TABLE FUNCIONARIO (
  COD_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR (250) NOT NULL,
  LOGIN VARCHAR (250) NOT NULL UNIQUE,
  SENHA VARCHAR (50) NOT NULL,
  NIVEL_ACESSO ENUM('1', '2', '3') NOT NULL DEFAULT '1'
);


DROP TABLE IF EXISTS PRODUTO;
CREATE TABLE PRODUTO (
  COD_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR (250) NOT NULL,
  DESCRICAO VARCHAR (250)
);

DROP TABLE IF EXISTS VARIACAO;
CREATE TABLE VARIACAO (
  COD_VARIACAO INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR (250) NOT NULL,
  PORCENTAGEM_DESCONTO DECIMAL (5,2),
  VALOR_DESCONTO DECIMAL (9,2),
  VALOR_INICIAL DECIMAL (9,2) NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS GRUPO_VARIACOES;
CREATE TABLE GRUPO_VARIACOES (
  COD_GRUPO_VARIACOES INT AUTO_INCREMENT,
  TIPO VARCHAR (250) NOT NULL,
  FK_COD_PRODUTO INT NOT NULL,
  FK_COD_VARIACAO INT NOT NULL,
  PRIMARY KEY (COD_GRUPO_VARIACOES, FK_COD_PRODUTO, FK_COD_VARIACAO),
  FOREIGN KEY (FK_COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
  FOREIGN KEY (FK_COD_VARIACAO) REFERENCES VARIACAO(COD_VARIACAO)
);

DROP TABLE IF EXISTS PEDIDO;
CREATE TABLE PEDIDO (
  COD_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
  VALOR_TOTAL DECIMAL (9,2) NOT NULL,
  VALOR_COM_DESCONTO DECIMAL (9,2),
  DATA_PEDIDO DATETIME NOT NULL,
  DATA_ENTREGA DATETIME NOT NULL,
  DATA_PAGAMENTO DATETIME NOT NULL,
  -- ENDERECO ENTREGA
  COMPLEMENTO VARCHAR (250),
  BAIRRO VARCHAR (250) NOT NULL,
  NUMERO VARCHAR(5) NOT NULL,
  RUA VARCHAR (250) NOT NULL,
  CEP CHAR (8),
  -- 
  FORMA_PAGAMENTO ENUM('PIX', 'CRÉDITO', 'DÉBITO', 'DINHEIRO'),
  STATUS_PEDIDO ENUM('FEITO', 'EM PREPARO', 'PRONTO', 'DESPACHADO', 'ENTREGUE', 'PAGO'),
  FK_COD_CLIENTE INT NOT NULL,
  FK_COD_FUNCIONARIO INT NOT NULL,
  FK_COD_CUPOM INT,
  FK_COD_ENDERECO INT,
  FOREIGN KEY (FK_COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE),
  FOREIGN KEY (FK_COD_FUNCIONARIO) REFERENCES FUNCIONARIO(COD_FUNCIONARIO),
  FOREIGN KEY (FK_COD_ENDERECO) REFERENCES ENDERECO(COD_ENDERECO)
);

DROP TABLE IF EXISTS PEDIDO_PRODUTO;
CREATE TABLE PEDIDO_PRODUTO (
  COD_PEDIDO_PRODUTO INT AUTO_INCREMENT,
  QUANTIDADE INT NOT NULL,
  SUBTOTAL INT,
  FK_COD_PEDIDO INT NOT NULL,
  FK_COD_PRODUTO INT NOT NULL,
  PRIMARY KEY(COD_PEDIDO_PRODUTO, FK_COD_PEDIDO, FK_COD_PRODUTO),
  FOREIGN KEY (FK_COD_PEDIDO) REFERENCES PEDIDO(COD_PEDIDO),
  FOREIGN KEY (FK_COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
);

DROP TABLE IF EXISTS PEDIDO_PRODUTO_GRUPO_VARIACOES;
CREATE TABLE PEDIDO_PRODUTO_GRUPO_VARIACOES (
  COD_PEDIDO_PRODUTO_GRUPO_VARIACOES INT AUTO_INCREMENT,
  FK_COD_VARIACAO INT NOT NULL,
  FK_COD_PEDIDO_PRODUTO INT NOT NULL,
  FK_COD_GRUPO_VARIACOES INT NOT NULL,
  PRIMARY KEY (COD_PEDIDO_PRODUTO_GRUPO_VARIACOES, FK_COD_PEDIDO_PRODUTO, FK_COD_GRUPO_VARIACOES),
  FOREIGN KEY (FK_COD_VARIACAO) REFERENCES VARIACAO(COD_VARIACAO),
  FOREIGN KEY (FK_COD_PEDIDO_PRODUTO) REFERENCES PEDIDO_PRODUTO(COD_PEDIDO_PRODUTO),
  FOREIGN KEY (FK_COD_GRUPO_VARIACOES) REFERENCES GRUPO_VARIACOES(COD_GRUPO_VARIACOES)
);

-- INSERT PRA TESTES
INSERT INTO `ENDERECO`(`COD_ENDERECO`, `NOME`, `COMPLEMENTO`, `BAIRRO`, `NUMERO`, `RUA`, `CEP`, `FK_COD_CLIENTE`) VALUES (0, "casa", "casa", "fds", 99, "Danone gay", "12345678", 0);
INSERT INTO `CLIENTE`(`COD_CLIENTE`, `NOME`, `EMAIL`, `SENHA`, `TELEFONE`) VALUES (0, "danone", "danifedosantos@gmail.com", "123", "12345678909");
INSERT INTO `CUPOM`(`COD_CUPOM`, `NOME`, `PORCENTAGEM_DESCONTO`, `VALOR_DESCONTO`, `DATA_VALIDADE`, `QUANTIDADE`) VALUES (0, "DANONE22", 22, 22.22, NOW(), 2222);
INSERT INTO `FUNCIONARIO`(`COD_FUNCIONARIO`, `NOME`, `NIVEL_ACESSO`, `LOGIN`, `SENHA`) VALUES (0, "Ro", "1", "ro.mudou@gmail.com", "QUEM FOI O MONSTRO ;-;");
INSERT INTO `PRODUTO`(`COD_PRODUTO`, `NOME`, `DESCRICAO`) VALUES (0, "FEJUCA", "BOM D+");
INSERT INTO `VARIACAO`(`COD_VARIACAO`, `NOME`, `PORCENTAGEM_DESCONTO`, `VALOR_DESCONTO`, `VALOR_INICIAL`) VALUES (0, "FEIJÃO PRETO", 0, 0, 0);
INSERT INTO `GRUPO_VARIACOES`(`COD_GRUPO_VARIACOES`, `TIPO`, `FK_COD_PRODUTO`, `FK_COD_VARIACAO`) VALUES (0, "ARROZ", 0, 0);
INSERT INTO `PEDIDO`(`COD_PEDIDO`, `VALOR_TOTAL`, `VALOR_COM_DESCONTO`, `DATA_PEDIDO`, `DATA_ENTREGA`, `DATA_PAGAMENTO`, `COMPLEMENTO`, `BAIRRO`, `NUMERO`, `RUA`, `CEP`, `FORMA_PAGAMENTO`, `STATUS_PEDIDO`, `FK_COD_CLIENTE`, `FK_COD_FUNCIONARIO`, `FK_COD_CUPOM`, `FK_COD_ENDERECO`) VALUES (0, 32.99, 32.99, NOW(), NOW(), NOW(), "casa", "fds", 99, "Danone gay", "12345678", "PIX", "FEITO", 0, 0, 0, 0);
INSERT INTO `PEDIDO_PRODUTO`(`COD_PEDIDO_PRODUTO`, `QUANTIDADE`, `SUBTOTAL`, `FK_COD_PEDIDO`, `FK_COD_PRODUTO`) VALUES (0, 1, 32.99, 0, 0);
INSERT INTO `PEDIDO_PRODUTO_GRUPO_VARIACOES`(`COD_PEDIDO_PRODUTO_GRUPO_VARIACOES`, `FK_COD_VARIACAO`, `FK_COD_PEDIDO_PRODUTO`, `FK_COD_GRUPO_VARIACOES`) VALUES (0, 0, 0, 0);

-- -- SELECT PRA TESTES

-- SELECT * FROM ENDERECO;
-- SELECT * FROM CLIENTE;
-- SELECT * FROM CUPOM;
-- SELECT * FROM FUNCIONARIO;
-- SELECT * FROM PRODUTO;
-- SELECT * FROM VARIACAO;
-- SELECT * FROM GRUPO_VARIACOES;
-- SELECT * FROM PEDIDO;
-- SELECT * FROM PEDIDO_PRODUTO;
-- SELECT * FROM PEDIDO_PRODUTO_GRUPO_VARIACOES;

-- -- DELETE PRA TESTES

-- DELETE FROM ENDERECO WHERE COD_ENDERECO = 0
-- DELETE FROM CLIENTE WHERE COD_CLIENTE = 0
-- DELETE FROM CUPOM WHERE COD_CUPOM = 0
-- DELETE FROM FUNCIONARIO WHERE COD_FUNCIONARIO = 0
-- DELETE FROM PRODUTO WHERE COD_PRODUTO = 0
-- DELETE FROM VARIACAO WHERE COD_VARIACAO = 0
-- DELETE FROM GRUPO_VARIACOES WHERE COD_GRUPO_VARIACOES = 0
-- DELETE FROM PEDIDO WHERE COD_PEDIDO = 0
-- DELETE FROM PEDIDO_PRODUTO WHERE COD_PEDIDO_PRODUTO = 0
-- DELETE FROM PEDIDO_PRODUTO_GRUPO_VARIACOES WHERE COD_PEDIDO_PRODUTO_GRUPO_VARIACOES = 0

-- CASO DE MERDA NAS FOREIGN KEY

-- -- ENDERECO
-- ALTER TABLE ENDERECO
-- ADD CONSTRAINT
-- FK_ENDERECO_TEM_COD_CLIENTE
-- FOREIGN KEY (FK_COD_CLIENTE)
-- REFERENCES CLIENTE(COD_CLIENTE);

-- -- PEDIDO
-- ALTER TABLE PEDIDO
-- ADD CONSTRAINT
-- FK_PEDIDO_TEM_COD_CLIENTE
-- FOREIGN KEY (FK_COD_CLIENTE)
-- REFERENCES CLIENTE(COD_CLIENTE);

-- ALTER TABLE PEDIDO
-- ADD CONSTRAINT
-- FK_PEDIDO_TEM_COD_FUNCIONARIO
-- FOREIGN KEY (FK_COD_FUNCIONARIO)
-- REFERENCES FUNCIONARIO(COD_FUNCIONARIO);

-- ALTER TABLE PEDIDO
-- ADD CONSTRAINT
-- FK_PEDIDO_TEM_COD_CUPOM
-- FOREIGN KEY (FK_COD_CUPOM)
-- REFERENCES CUPOM(COD_CUPOM);

-- ALTER TABLE PEDIDO
-- ADD CONSTRAINT
-- FK_PEDIDO_TEM_COD_ENDERECO
-- FOREIGN KEY (FK_COD_ENDERECO)
-- REFERENCES ENDERECO(COD_ENDERECO);

-- -- PEDIDO PRODUTO
-- ALTER TABLE PEDIDO_PRODUTO
-- ADD CONSTRAINT
-- FK_PEDIDO_PRODUTO_TEM_COD_PEDIDO
-- FOREIGN KEY (FK_COD_PEDIDO)
-- REFERENCES PEDIDO(COD_PEDIDO);

-- ALTER TABLE PEDIDO_PRODUTO
-- ADD CONSTRAINT
-- FK_PEDIDO_PRODUTO_TEM_COD_PRODUTO
-- FOREIGN KEY (FK_COD_PRODUTO)
-- REFERENCES PRODUTO(COD_PRODUTO);

-- -- GRUPO VARIACOES
-- ALTER TABLE GRUPO_VARIACOES
-- ADD CONSTRAINT
-- FK_GRUPO_VARIACOES_TEM_COD_PRODUTO
-- FOREIGN KEY (FK_COD_PRODUTO)
-- REFERENCES PRODUTO(COD_PRODUTO);

-- ALTER TABLE GRUPO_VARIACOES
-- ADD CONSTRAINT
-- FK_GRUPO_VARIACOES_TEM_COD_VARIACOES
-- FOREIGN KEY (FK_COD_VARIACOES)
-- REFERENCES VARIACAO(COD_VARIACAO);

-- -- PEDIDO PRODUTO GRUPO VARIACOES
-- ALTER TABLE PEDIDO_PRODUTO_GRUPO_VARIACOES
-- ADD CONSTRAINT
-- FK_PEDIDO_PRODUTO_GRUPO_VARIACOES_TEM_COD_GRUPO_VARIACOES
-- FOREIGN KEY (FK_COD_GRUPO_VARIACOES)
-- REFERENCES GRUPO_VARIACOES(COD_GRUPO_VARIACOES);

-- ALTER TABLE PEDIDO_PRODUTO_GRUPO_VARIACOES
-- ADD CONSTRAINT
-- FK_PEDIDO_PRODUTO_GRUPO_VARIACOES_TEM_COD_PEDIDO_PRODUTO
-- FOREIGN KEY (FK_COD_PEDIDO_PRODUTO)
-- REFERENCES PEDIDO_PRODUTO(COD_PEDIDO_PRODUTO);

-- ALTER TABLE PEDIDO_PRODUTO_GRUPO_VARIACOES
-- ADD CONSTRAINT
-- FK_PEDIDO_PRODUTO_GRUPO_VARIACOES_TEM_COD_VARIACAO
-- FOREIGN KEY (FK_COD_VARIACAO)
-- REFERENCES VARIACAO(COD_VARIACAO);